config/routes.rb
Rails.application.routes.draw do
  get 'contact/our'

  get 'contact/story'

  root 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def our
  end

  def story
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact/our.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Shop Betty
                    </a>
                </li>
                <li>
                    <a href="#">Our Story</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
                <li>
                    <a href="#">Social</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
<br>
<br>
<center><a href="http://tinypic.com?ref=2cgf0xj" target="_blank"><img src="http://i63.tinypic.com/2cgf0xj.png" border="0" alt="Image and video hosting by TinyPic"></a></center>

<br>
<br>
<br>
<br>
<br>
<br>
 <img style="float: left; margin: 20px 75px 15px 125px;" src="http://i63.tinypic.com/30b1a54.jpg" />

 <h2>'The Sculpting' Powder</h2>
 <h3>$44</h3>
<br>
<br>
 <a href="http://tinypic.com?ref=ouoyo2" target="_blank"><img src="http://i67.tinypic.com/ouoyo2.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<br>
<a href="http://tinypic.com?ref=2ezhbmp" target="_blank"><img src="http://i65.tinypic.com/2ezhbmp.png" border="0" alt="Image and video hosting by TinyPic"></a>

app/views/contact/story.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Shop Betty
                    </a>
                </li>
                <li>
                    <a href="#">Our Story</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
                <li>
                    <a href="#">Social</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
<br>
<br>
<center><a href="http://tinypic.com?ref=2cgf0xj" target="_blank"><img src="http://i63.tinypic.com/2cgf0xj.png" border="0" alt="Image and video hosting by TinyPic"></a></center>









<form method="post" action="#">
  <div class="group">
    <div class="left">
      First Name
      <input type="text" value="" placeholder="" name="name" tabindex="1" class="redacted" />
    </div>
    <div class="right">
      Last Name
      <input type="text" value="" placeholder="" name="subject" tabindex="2" class="redacted" />
    </div>
  </div>
  <div class="group">
    <div class="left">
      Email
      <input type="text" value="" placeholder="" name="email" tabindex="3" class="redacted" />
    </div>
    <div class="right">
      My Question
      <input type="text" value="" placeholder="" name="phone" tabindex="4" class="redacted" />
    </div>
  </div>
  <div>
    Contact
    <textarea placeholder="" name="message" tabindex="5" rows="10" class="redacted"></textarea>
  </div>
  <br>
  <div>
    <input type="button" value="Send Mail" tabindex="6" class="redacted" />
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> 💕Shop Betty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/hello.html.erb
<h1>Pages#helo</h1>
<p>Find me in app/views/pages/helo.html.erb</p>

app/views/pages/welcome.html.erb
<h1>Pages#welcomenme</h1>
<p>Find me in app/views/pages/welcomenme.html.erb</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

 

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        
                    </a>
                </li>
                <li>
                    <li><%= link_to "Contact Us", contact_story_path %></li>
                </li>
                <li>
                    <a href="#">Our Story</a>
                </li>
                <li>
                    <a href="#">Social Media</a>
                </li>
                <li>
                   
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
<br>
<br>
<center><a href="http://tinypic.com?ref=2cgf0xj" target="_blank"><img src="http://i63.tinypic.com/2cgf0xj.png" border="0" alt="Image and video hosting by TinyPic"></a></center>




        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header"></h1>
            </div>

            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/671534/671534_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/664793/664793_in_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/671974/671974_in_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/668970/668970_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/650459/650459_in_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/667965/667965_fr_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/664184/664184_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/633081/633081_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/669379/669379_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                    <br>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/650461/650461_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/337112/337112_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <img class="img-responsive" src="https://cache.net-a-porter.com/images/products/594989/594989_ou_sl.jpg" alt="">
                    <br>
                    <center><t>2015 Holiday Barbie™ Doll</t></center>
                    <br>
                    <center><t>$50</t></center>
                </a>
            </div>
        </div>
              

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="3VNHYQAZKCD36">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>